### ISSUE TITLE
Error while installing with PIP

### ISSUE THREAD

**Issue by zahari** [kiwitcms/python-social-auth-kerberos#3]
```
zahari@astra:~$ pip install social-auth-kerberos
Collecting social-auth-kerberos
  Downloading https://files.pythonhosted.org/packages/b0/b2/20b7be00ae9242043c105dce3918ce16d50ba67f4f3e22126c4713e7b666/social-auth-kerberos-0.2.1.tar.gz
Collecting gssapi (from social-auth-kerberos)
  Downloading https://files.pythonhosted.org/packages/f7/17/1a316f0c6a1b802a9b4d6253068b4a3756cfef19fbd43d9747839d98ff30/gssapi-1.5.1.tar.gz (965kB)
    100% |████████████████████████████████| 972kB 476kB/s 
    Complete output from command python setup.py egg_info:
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Nfc5w8/gssapi/setup.py", line 109, in <module>
        raise Exception("Could not find main GSSAPI shared library.  Please "
    Exception: Could not find main GSSAPI shared library.  Please try setting GSSAPI_MAIN_LIB yourself or setting ENABLE_SUPPORT_DETECTION to 'false'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Nfc5w8/gssapi/
```

**Comment by zahari** [comment]
Workaround:
```
sudo apt-get install libkrb5-dev
pip install gssapi
```

**Comment by atodorov** [comment]
So missing krb5-dev is the culprit. From what I can tell gssapi ships only a tarball, no wheel package and this is compiled at install time.

We also ship only a tarball for social-auth-kerberos but we can easily start pushing precompiled wheels as well. 

Nothing else we can do here really - if dependencies need devel files they need them.

**Comment by atodorov** [comment]
@zahari maybe document the issue in readme? what do you think?

**Comment by zahari** [comment]
Exactamente
